# -*- coding: utf-8 -*-
"""250423.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gS1W87raBfzSKpbZh7M9fiQrW9YC_oFX
"""

import pandas as pd
from pandas import Series
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    '이름':["철수","영희","민수"],
    "나이":[25,30,22],
    "성별":["남자","여자","남자"],
    "점수":[90, 85,95]
    }

dif= pd.DataFrame(data)
dif

dif.loc[[1,2],["점수","이름"]]

female_names = dif[dif["성별"] == "여자"]["이름"]
female_names

male_high_score = dif[(dif['성별']=='남자')&(dif['점수']>=95)]
male_high_score



plt.style.use("ggplot")

plt.figure(figsize=(15,6))
sns.lineplot(
                    x='date',
                    y='americano',
                    data=df,
                    maker='o'
)
plt.title("아메리카노 판매량")
plt.xlabel("날짜")
plt.ylabel("판매량")
plt.tight_layout()
plt.show()

ages = Series([25, 30, 22, 29,43,34])

ages

ex_data = {
    "학생이름":["김철수","이영희","박지민"],
    "나이":[25,30,22],
    "키":[183, 153,162]
}

ex_df = pd.ex_DataFrame(data)
ex_df

df = pd.read_csv("cafe_1.csv")
df .head()

df.info()

df.describe()  # 전체테이블을 볼수있고
df.describe().loc[["max","mean","50%",]]#.loc으로 필요한값만 선택해서 볼수있다.

class Product:
    def __init__(self, name, price,stock):
        self.name = name
        self.price = price
        self.stock = stock
    def show_info(self):
        print(f"\t 상품명 : {self.name},  가격 : {self.price},  재고 : {self.stock}")
        print("========================================================")
    def apply_discount(self,discount_rate):
        self.price = self.price -discount_rate
        print(f"할인된 가격은 {self.price}원 입니다.")
    def buy_product(self, quantity):

            if quantity > self.stock:
                    print("재고가 부족합니다.")
            else:
                    self.stock = self.stock - quantity
                    print(f"{quantity}개 구매 완료!  \n 남은 재고: {self.stock}개")
                    print("========================================================")
    def add_product(self, quantity):
            self.stock = self.stock + quantity
            print(f"{self.name}상품을 {quantity}개 추가했습니다.   \n 남은 재고: {self.stock}개")
            print("========================================================")

Product1 = Product("노트북",1000000,10)

Product1
Product1.show_info()

Product1.buy_product(3)

Product1.add_product(2)



class Car:
    def __init__(self, color, brand, max_speed):
        self.color = color
        self.brand = brand
        self.max_speed = max_speed
    def drive(self):
        print(f"{self.brand}차가 {self.max_speed}으로 갑니다.")
        print("부우우우우우우~~~~~~~~~")
    def stop(self):
        print(f"{self.brand}차가 멈춥니다."  )
        print("끼이이이읶!!!!!")

my_car = Car("빨간색","현대",5000000)

print(my_car.color)
my_car.color = "파란색"
print(my_car.color)

my_car.drive()