# -*- coding: utf-8 -*-
"""250422.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ffrnLgS56TEE3f3n38yggn5bn3mQRRqz
"""

orders_date = [
    {"고객명":"철수", "구매일":"2024-01-01"},
    {"고객명":"영희", "구매일":"2023-10-10"}
]

inactive_customers=[]
for order_date in orders_date:
    late_date = today - datetime.strptime(order_date["구매일"],"%Y-%m-%d")
    print(late_date.days)
    if late_date.days > 500:
        inactive_customers.append(order_date["고객명"])
print(inactive_customers)

from datetime import datetime

cutoff = datetime(2024,10,1)

cutoff

today  = datetime.strptime("2025-04-22","%Y-%m-%d")
today

(today - cutoff).days

orders = {
    "김철수":{"김치찌개":1, "불고기":2},
    "이영희":{"된장찌개":2, "비빔밥":5}
}

for customer,menu in orders.items():
    print(f"{customer}님의 주문내역 : ")
    for dmenu,qty in menu.items():
        print(f"- {dmenu} : {qty}개")

print(orders)
for customer, menu in orders.items():
    print(f"{customer}는 ",end ="")
    for item, count in menu.items():
        print(f"{item}를  {count}개 시켰습니다.")

scores = [10, -5, 20, -15, 0]

status = ["Positive" if s > 0 else "Negative" if s < 0 else "Zero" for s in scores]

print(status)

sooress = [s*5 for s in scores]
print(sooress)

import time
time.time()

time.time()

start = time.time()
lst = []
for i in range(1,100000101):
    lst.append(i*2)
end = time.time()
print(f"{end-start}초 걸림")

com_lst = [i *2for i in range(1,1000)]
print(com_l)

even_num = [i for i in range(1,101) if i % 2 == 0]
print(even_num)

cart = []
while True:
    print("\n==================")
    print("====장바구니======")
    print("==================")
    print("1.장바구니 보기")
    print("2.장바구니 담기")
    print("3.장바구니 비우기")
    print("4.장바구니 물건빼기")
    print("5.장바구니 종료")
    print("==================")
    menu = input("메뉴를 선택하세요 : ")
    if menu == '1':
        if cart:
            for i in range(len(cart)):
                print(f"{i+1}.{cart[i]}")
        else:
            print("장바구니가 비었습니다.")
    elif menu == '2':
        item = input("장바구니에 담을 상품을 입력하세요 : ")
        cart.append(item)
        print(f"{item}이 장바구니에 담겼습니다.")
    elif menu == '3':
        cart.clear()
        print("장바구니가 비었습니다.")
    elif menu == '4':
        if cart:
            del_item = input("장바구니에서 제거할 상품을 입력하세요 : ")
            if del_item in cart:
                cart.remove(del_item)
                print(f"{del_item}이 장바구니에서 제거되었습니다.")
            else:
                print(f"{del_item}은 장바구니에 없습니다.")
        else:
            print("장바구니가 비었습니다.")
    elif menu == '5':
        print("장바구니 프로그램을 종료합니다.")
        break
    else:
        print("잘못입력하셨습니다. 1-5중에 입력해주세요!")

str = map(input().sprit('-'))

def introduction(name= '홍길동',age =20, *hobby):
    print(f"안녕하세요? {name} 입니다")
    print(f"{age}살 입니다.")
    if hobby:
        print("제 취미는")
        for h in hobby:
            print(f"{h}\t",end="")
        print("입니다.")
    else:
        print("취미가 없습니다.")
    print("==================================")

introduction("이혁",24)
introduction("오성민",29,"러닝","게임","코딩","맛집탐방")



import random
def lucky(start=1,last = 45):
    num = random.randint(start,last)
    print(f"오늘의 행운수는 {num}입니다")

lucky()

print("로또생성기 6/45")
for i in range(6):
    lucky(1,45)

def box(*objs):
    i =0
    print("\n\nbox안에 물건들 목록입니다\n====================================")
    for obj in objs:
        i+=1
        print(f"{i}번째 물건은 {obj}입니다")

box("사과","바나나")
box("사과","바나나","오렌지","수박","키위")
box()

list1 = ["사과","오렌지;","바나나"]
print(list1)
list1[1] = "딸기"
print(list1)

cook_ramen()

def cook_ramen(water = 400, ramen = "진라면", suop = "순한맛"):
    print(f"{water}ml 물을 넣고 끓입니다. 보글보글")
    print(f"{ramen}을 넣습니다. 보글보글")
    print(f"{suop}을 넣습니다. 보글보글")
    print(f"{ramen} 완성! 맛있게 드세요")

cook_ramen(ramen="안성탕면")

cook_ramen(500,"신라면", "매운맛 스프")
cook_ramen(300,"짜파게티", "짜장맛 스프")

cook_ramen(suop = "구수한맛 스프",water=450,ramen="튀김우동")